// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxawssvosysharsvbqlq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94YXdzc3Zvc3lzaGFyc3ZicWxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMTQ5MDMsImV4cCI6MjA2MTc5MDkwM30.T0OjZw5bBj0Hu2wK_BCsNwXqqAzdv-JRAdTM5k6h_Fs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);